version: '2'
services:
    nginx:
        container_name: piccolle_nginx
        image: nginx:1.11.5-alpine
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - ./htdocs/:/usr/share/nginx/htdocs/
        ports:
            - 80:80
        links:
            - app
        command: nginx -g 'daemon off';

    app:
        container_name: piccolle_app
        image: python:3.5.2-alpine
        ports:
            - 8000:8000
