version: '2'
services:
    nginx:
        container_name: piccolle_nginx
        image: nginx:1.11.5-alpine
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - ./htdocs/:/usr/share/nginx/htdocs/
            - ./keys/:/usr/share/nginx/keys/
        ports:
            - 80:80
            - 443:443
        links:
            - app
        command: nginx -g 'daemon off';

    app:
        container_name: piccolle_app
        image: python:3.5.2-alpine
        volumes:
            - ./app/:/mnt/
        expose:
            - 5000
        working_dir: /mnt
        environment:
            - FLASK_APP=main.py
        #command: ash -c 'pip install Flask beautifulsoup4 && python -m flask run --host=0.0.0.0'
        tty: true
        command: ash -c 'pip install Flask beautifulsoup4 && ash'
