version: '2'
services:
    nginx:
        container_name: piccolle_nginx
        image: nginx:1.11.5-alpine
        volumes:
            - ./serve/default.conf:/etc/nginx/conf.d/default.conf
            - ./serve/keys/:/usr/share/nginx/keys/
            - ./htdocs/:/usr/share/nginx/htdocs/
        ports:
            - 80:80
            - 443:443
        links:
            - app
        command: nginx -g 'daemon off';

    app:
        container_name: piccolle_app
        build: ./app
        volumes:
            - ./app/:/mnt/
        links:
            - phantomjs
        expose:
            - 5000
        working_dir: /mnt
        environment:
            - FLASK_APP=main.py
        command: python -m flask run --host=0.0.0.0

    phantomjs:
        container_name: piccolle_phantomjs
        image: wernight/phantomjs:2.1.1
        expose:
            - 8910
        command: phantomjs --webdriver=8910
